stages:
  - test
  - build

services:
  - postgres:14.2-bullseye

variables:
  DATABASE_URL: postgresql://winery:password@postgres/winery
  POSTGRES_MULTIPLE_DATABASES: winery
  POSTGRES_PASSWORD: test-databases
  WAIT_HOSTS: postgres:5432


# TEST 
lint-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 sales inventory

# BUILD
build-front-end-job:
  stage: build
  image: node:lts-bullseye
  script:
    - cd ghi
    - npm install
    - npm run build
    # - echo ${REACT_APP_DJANGO_API}
