stages:
  - test 
  - build
  - deploy

services:
  - postgres:14.2-bullseye

variables:
  DATABASE_URL: postgresql://postgres:test@postgres:5432/postgres

winery-unit-test-job:
  image: python:3-bullseye
  stage: test
  script: 
    - cd winery
    - pip install -r requirements.txt
    - python -m pytest
  allow_failure: true
  
  


lint-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 winery sales
  allow_failure: true
  

build-front-end-job:
  stage: build
  image: node:lts-bullseye
  variables:
    PUBLIC_URL: https://beach-bums.gitlab.io/everything-is-vine
  script:
    - cd ghi  # CHANGE THIS TO THE DIRECTORY THAT HAS package.json
    - npm install
    - npm run build
    - cp build/index.html build/404.html  # Make this a SPA
  
  artifacts:
    paths:
      - ghi/build/  # Save all of the files in the build path
  



    



