stages:
  - test
  - build
  - deploy

variables:
  DATABASE_URL: postgresql://winery:password@postgres/winery
  POSTGRES_MULTIPLE_DATABASES: winery,sales
  POSTGRES_PASSWORD: test-databases
  WAIT_HOSTS: postgres:5432


# TEST 
lint-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 service-sales service-winery

# BUILD
build-front-end-job:
  stage: build
  image: node:lts-bullseye
  variables:
    PUBLIC_URL: https://beach-bums.gitlab.io/everything-is-vine
  script:
    - cd ghi
    - npm install
    - npm run build
    # - echo ${REACT_APP_DJANGO_API}
  artifacts:
    paths:
      - ghi/build
    pages:
      stage: deploy
      rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      dependencies:
        - build-front-end-job
      needs:
        - build-front-end-job
      script:
        - mv ghi/build/ public
      artifacts:
        paths:
          - public


heroku-inventory-api-image-job:
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    stage: build
    image: docker:20.10.16
    services:
      - docker:20.10.16-dind
    script:
      - cd winery
      - docker build -t ${CI_REGISTRY_IMAGE}/winery_api:latest .
      - docker tag ${CI_REGISTRY_IMAGE}/winery_api:latest ${CI_REGISTRY_IMAGE}/winery_api:$CI_JOB_ID
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
      - docker push ${CI_REGISTRY_IMAGE}/winery_api:$CI_JOB_ID
      - docker push ${CI_REGISTRY_IMAGE}/winery_api:latest

deploy-inventory-api-image-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    - heroku-inventory-api-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    - docker pull ${CI_REGISTRY_IMAGE}/winery_api:latest
    - docker tag ${CI_REGISTRY_IMAGE}/winery_api:latest registry.heroku.com/$HEROKU_SERVICE_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_SERVICE_APP/web:latest

release-winery-api-image-job:
  stage: deploy
  image: node:10.17-alpine
  needs:
    - deploy-inventory-api-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - heroku container:release web --app $HEROKU_INVENTORY_API_APP


