stages:
  - test

variables:
  DATABASE_URL: postgresql://winery:password@postgres/winery
  POSTGRES_MULTIPLE_DATABASES: winery,sales
  POSTGRES_PASSWORD: test-databases
  WAIT_HOSTS: postgres:5432

lint-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 service-sales service-winery


  build-front-end-job:
    stage: build
    image: node:lts-bullseye
    script:
      - cd ghi
      - npm install
      -npm run build

# stages:
#   - test # Run tests
  # - build # Build assets

# services:
#   - postgres:14.2-bullseye

# variables:
#   POSTGRES_PASSWORD: test
#   DATABASE_URL: postgresql://postgres:test@postgres:5432/postgres
#   REACT_APP_DJANGO_API: https://${HEROKU_DJANGO_API_APP}.herokuapp.com

## TESTING
# fast-api-unit-test-job:
# image: python:3-bullseye
# stage: test
# script:
#   - cd winery
#   - pip install -r requirements.txt
#   - python -m pytest

# django-api-unit-test-job:
#   image: python:3-bullseye
#   stage: test
#   script:
#     - cd winery
#     - pip install -r requirements.txt
#     - python -m pytest

# lint-python-projects-job:
#   image: python:3-bullseye
#   stage: test
#   script:
#     - pip install flake8
#     - flake8 winery sales

## BUILD
# ghi-build-job:
#   stage: build
#   image: node:lts-bullseye
#   script:
#     - cd ghi
#     - npm install
#     - npm run build
#     - echo ${REACT_APP_DJANGO_API}

